### ISSUE TITLE
26 Errors - While Compiling

### ISSUE THREAD

**Issue by alexmplays** [GRGServer/SAMPRacing#2]
SAMPRacing-master\pawno\include\edgerally/globals.inc(3) : error 017: undefined symbol "E_COMMANDALIAS"

SAMPRacing-master\pawno\include\edgerally/globals.inc(3) : error 009: invalid array size (negative, zero or out of bounds)

SAMPRacing-master\pawno\include\edgerally/globals.inc(12) : error 017: undefined symbol "E_OBJECTMODEL"

SAMPRacing-master\pawno\include\edgerally/globals.inc(12) : error 009: invalid array size (negative, zero or out of bounds)

SAMPRacing-master\pawno\include\edgerally/globals.inc(22) : error 017: undefined symbol "E_TUNINGPART"

SAMPRacing-master\pawno\include\edgerally/globals.inc(24) : error 017: undefined symbol "E_VEHICLEMODEL"

SAMPRacing-master\pawno\include\edgerally/globals.inc(24) : error 009: invalid array size (negative, zero or out of bounds)

SAMPRacing-master\pawno\include\edgerally/globals.inc(25) : error 017: undefined symbol "E_VEHICLESHOP"

SAMPRacing-master\pawno\include\edgerally/functions/AddObject.inc(29) : error 017: undefined symbol "GetObjectNameByModelID"

SAMPRacing-master\pawno\include\edgerally/functions/AddObject.inc(31) : error 017: undefined symbol "UpdateObjectEditorInfo"

SAMPRacing-master\pawno\include\edgerally/functions/DeleteVehicle.inc(9) : error 017: undefined symbol "DestroyVehicleEx"

SAMPRacing-master\pawno\include\edgerally/functions/EnterGarage.inc(13) : error 017: undefined symbol "DestroyVehicleEx"

SAMPRacing-master\pawno\include\edgerally/functions/ExecuteCommand.inc(14) : error 017: undefined symbol "GetPlayerNameEx"

SAMPRacing-master\pawno\include\edgerally/functions/ExecuteCommand.inc(41) : error 017: undefined symbol "E_COMMANDALIAS_NAME"

SAMPRacing-master\pawno\include\edgerally/functions/ExecuteCommand.inc(44) : error 017: undefined symbol "E_COMMANDALIAS_PARAMETERS"

SAMPRacing-master\pawno\include\edgerally/functions/ExecuteCommand.inc(45) : error 017: undefined symbol "E_COMMANDALIAS_PARAMETERS"

SAMPRacing-master\pawno\include\edgerally/functions/ExecuteCommand.inc(51) : error 017: undefined symbol "E_COMMANDALIAS_COMMAND"

SAMPRacing-master\pawno\include\edgerally/functions/ExecuteCommand.inc(63) : error 017: undefined symbol "OnPlayerCommandPerformed"

SAMPRacing-master\pawno\include\edgerally/functions/GetPlayerID.inc(5) : error 017: undefined symbol "GetPlayerNameEx"

SAMPRacing-master\pawno\include\edgerally/functions/ReloadAreas.inc(55) : error 004: function "XML_GetFloatValue" is not implemented

SAMPRacing-master\pawno\include\edgerally/functions/ReloadAreas.inc(62) : error 004: function "XML_GetFloatValue" is not implemented

SAMPRacing-master\pawno\include\edgerally/functions/SaveRaces.inc(27) : error 017: undefined symbol "XML_SetIntAttribute"

SAMPRacing-master\pawno\include\edgerally/functions/SaveRaces.inc(34) : error 017: undefined symbol "XML_SetIntAttribute"

SAMPRacing-master\pawno\include\edgerally/functions/SaveRaces.inc(77) : error 017: undefined symbol "XML_SetIntAttribute"

SAMPRacing-master\pawno\include\edgerally/functions/SaveRaces.inc(75) : warning 204: symbol is assigned a value that is never used: "npcNode"

SAMPRacing-master\pawno\include\edgerally/functions/SendClientMessageEx.inc(67) : error 017: undefined symbol "GetPlayerNameEx"

SAMPRacing-master\pawno\include\edgerally/functions/SpawnVehicle.inc(37) : error 017: undefined symbol "CreateVehicleEx"

Compilation aborted.Pawn compiler 3.2.3664	 	 	Copyright (c) 1997-2006, ITB CompuPhase

26 Errors.

**Comment by Programie** [comment]
As that looks like you have modified the directory structure a bit: Are you sure you have included the files in the correct order? As far as I know, it is really important for the Pawn compiler to define functions, variables, etc. in the right order (and therefore include them in the right order).

**Comment by alexmplays** [comment]
i renamed it to edgerally i edit the compiler-windows.bat by changing grg to edgerally but still when i execute it doesnt compile the gamemode and it shows some errors (1 error i saw). After i tried to compile gamemode manually it shows this 26 errors.

**Comment by Programie** [comment]
Weird, those warnings and error messages look like some files were not included.

Are you able to successfully compile the gamemode if you simply clone this repository and just modify the required files (i.e. create the localconfig.inc)?
